/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    '工時填寫': typeof import('./src/components/workTime/工時填寫.vue')['default']
    '本周每日各專案堆疊圖': typeof import('./src/components/dashboard/本周每日各專案堆疊圖.vue')['default']
    '本週累計工時': typeof import('./src/components/dashboard/本週累計工時.vue')['default']
    '更新日誌': typeof import('./src/components/dashboard/更新日誌.vue')['default']
    '更新清單': typeof import('./src/components/dashboard/更新清單.vue')['default']
    '每日各專案耗用時數': typeof import('./src/components/dashboard/每日各專案耗用時數.vue')['default']
    '每日各專案議題': typeof import('./src/components/dashboard/每日各專案議題.vue')['default']
    '每日各專案議題議題耗用時數': typeof import('./src/components/dashboard/每日各專案議題議題耗用時數.vue')['default']
    '近期工時紀錄': typeof import('./src/components/workTime/近期工時紀錄.vue')['default']
    '待處理議題': typeof import('./src/components/dashboard/待處理議題.vue')['default']
    '待處理議題_old': typeof import('./src/components/dashboard/待處理議題_old.vue')['default']
    '活動清單': typeof import('./src/components/dashboard/活動清單.vue')['default']
    '參與中專案': typeof import('./src/components/dashboard/參與中專案.vue')['default']
    '逾期任務': typeof import('./src/components/dashboard/逾期任務.vue')['default']
    '議題狀態': typeof import('./src/components/dashboard/議題狀態.vue')['default']
    '議題狀態圓餅圖': typeof import('./src/components/dashboard/議題狀態圓餅圖.vue')['default']
    Chart: typeof import('./src/components/form/Chart.vue')['default']
    copy: typeof import('./src/components/workTime/ModelDelete copy.vue')['default']
    ModelDelete: typeof import('./src/components/workTime/ModelDelete.vue')['default']
    ModelM: typeof import('./src/components/workTime/ModelM.vue')['default']
    ModelUpdate: typeof import('./src/components/workTime/ModelUpdate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./src/components/SideMenu.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UBadge: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UColorModeSwitch: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/color-mode/ColorModeSwitch.vue')['default']
    UDashboardGroup: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue')['default']
    UDashboardNavbar: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DashboardNavbar.vue')['default']
    UDashboardPanel: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.vue')['default']
    UDashboardSidebar: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue')['default']
    UDropdownMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UForm: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UInputDate: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/InputDate.vue')['default']
    UInputNumber: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue')['default']
    UModal: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UProgress: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Progress.vue')['default']
    USelect: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USelectMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue')['default']
    USeparator: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Separator.vue')['default']
    USkeleton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue')['default']
    UTable: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
    UTabs: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
    UTextarea: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
  }
}
