/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    '本周每日各專案堆疊圖': typeof import('./src/components/dashboard/本周每日各專案堆疊圖.vue')['default']
    '本週累計工時': typeof import('./src/components/dashboard/本週累計工時.vue')['default']
    '待處理議題': typeof import('./src/components/dashboard/待處理議題.vue')['default']
    '待處理議題_old': typeof import('./src/components/dashboard/待處理議題_old.vue')['default']
    '參與中專案': typeof import('./src/components/dashboard/參與中專案.vue')['default']
    '逾期任務': typeof import('./src/components/dashboard/逾期任務.vue')['default']
    Chart: typeof import('./src/components/form/Chart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./src/components/SideMenu.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UColorModeSwitch: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/color-mode/ColorModeSwitch.vue')['default']
    UDashboardGroup: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue')['default']
    UDashboardNavbar: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DashboardNavbar.vue')['default']
    UDashboardPanel: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.vue')['default']
    UDashboardSidebar: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue')['default']
    UForm: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UProgress: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Progress.vue')['default']
    USelect: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USeparator: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Separator.vue')['default']
    USkeleton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue')['default']
    UTabs: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
  }
}
